#############################################################################
#                                                                           #
# appveyor.yml                                                              #
#                                                                           #
# Author: Denes Solti                                                       #
#                                                                           #
#############################################################################

# common configuration for ALL branches
image: Visual Studio 2019

environment:
  APPVEYOR_RDP_PASSWORD:
    secure: IvxSZoWD+DpqNjUP7mFjPA==
  COVERALLS_REPO_TOKEN:
    secure: CDOE0Xkqvh8MlC9FBj3tyXEvRYPGleKUctnzlosfIjEKlV4W0vl4++b1WOkDy3f5
  PYTHONPATH: src/pyconn;vendor;tests

build: off

clone_script:
  - cmd: |
      git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      git checkout -qf %APPVEYOR_REPO_COMMIT%

init:
  - ps: |
      $ErrorActionPreference = "Stop"
#     IEX ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - cmd: pip install -r "build_requirements.txt" -r "test_requirements.txt" -t "vendor" --no-user --disable-pip-version-check

build_script:
    - ps: python -m pylint (git ls-files '*.py')

test_script:
  - cmd: |
      python -m coverage run -m tests
      python -m coveralls

after_test:
 - ps: |
     $client=New-Object System.Net.WebClient

     Get-ChildItem -Path (Join-Path "artifacts" "*.xml") | foreach {
       Write-Host "Uploading test result: $($_.Name)"
       $client.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($Env:APPVEYOR_JOB_ID)", $_.FullName)
     }

on_finish:
  - ps: |
#     $blockRdp = $true; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))