#############################################################################
#                                                                           #
# appveyor.yml                                                              #
#                                                                           #
# Author: Denes Solti                                                       #
#                                                                           #
#############################################################################

# common configuration for ALL branches
image: Visual Studio 2019

environment:
  APPVEYOR_RDP_PASSWORD:
    secure: IvxSZoWD+DpqNjUP7mFjPA==
  PYTHONPATH: src;vendor;tests

build: off

clone_script:
  - cmd: |
      git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      git checkout -qf %APPVEYOR_REPO_COMMIT%

init:
  - ps: |
      $ErrorActionPreference = "Stop"
#     IEX ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_test:
  - cmd: pip install -r "requirements.txt" -t "vendor" --no-user --disable-pip-version-check

test_script:
  - cmd: python -m tests

after_test:
 - ps: |
     $client=New-Object System.Net.WebClient

     Get-ChildItem -Path (Join-Path "artifacts" "*.xml") | foreach {
       Write-Host "Uploading test result: $($_.Name)"
       $client.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($Env:APPVEYOR_JOB_ID)", $_.FullName)
     }


on_finish:
  - ps: |
#     $blockRdp = $true; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
